//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TATNegociaciones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TAT001Entities : DbContext
    {
        public TAT001Entities()
            : base("name=TAT001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCION> ACCIONs { get; set; }
        public virtual DbSet<ACCIONT> ACCIONTs { get; set; }
        public virtual DbSet<APPSETTING> APPSETTINGs { get; set; }
        public virtual DbSet<CALENDARIO_AC> CALENDARIO_AC { get; set; }
        public virtual DbSet<CALENDARIO_EX> CALENDARIO_EX { get; set; }
        public virtual DbSet<CAMPOS> CAMPOS { get; set; }
        public virtual DbSet<CAMPOZKE24> CAMPOZKE24 { get; set; }
        public virtual DbSet<CAMPOZKE24T> CAMPOZKE24T { get; set; }
        public virtual DbSet<CANAL> CANALs { get; set; }
        public virtual DbSet<CARPETA> CARPETAs { get; set; }
        public virtual DbSet<CARPETAT> CARPETATs { get; set; }
        public virtual DbSet<CARTA> CARTAs { get; set; }
        public virtual DbSet<CARTAP> CARTAPs { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<CATEGORIAT> CATEGORIATs { get; set; }
        public virtual DbSet<CITy> CITIES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<CLIENTEF> CLIENTEFs { get; set; }
        public virtual DbSet<CLIENTEI> CLIENTEIs { get; set; }
        public virtual DbSet<CONDICION> CONDICIONs { get; set; }
        public virtual DbSet<CONDICIONT> CONDICIONTs { get; set; }
        public virtual DbSet<CONFDIST_CAT> CONFDIST_CAT { get; set; }
        public virtual DbSet<CONMAIL> CONMAILs { get; set; }
        public virtual DbSet<CONPOSAPH> CONPOSAPHs { get; set; }
        public virtual DbSet<CONPOSAPP> CONPOSAPPs { get; set; }
        public virtual DbSet<CONSOPORTE> CONSOPORTEs { get; set; }
        public virtual DbSet<CONTACTOC> CONTACTOCs { get; set; }
        public virtual DbSet<COUNTRy> COUNTRIES { get; set; }
        public virtual DbSet<CUENTA> CUENTAs { get; set; }
        public virtual DbSet<CUENTAGL> CUENTAGLs { get; set; }
        public virtual DbSet<DELEGAR> DELEGARs { get; set; }
        public virtual DbSet<DET_AGENTE> DET_AGENTE { get; set; }
        public virtual DbSet<DET_AGENTEC> DET_AGENTEC { get; set; }
        public virtual DbSet<DET_AGENTEH> DET_AGENTEH { get; set; }
        public virtual DbSet<DET_AGENTEP> DET_AGENTEP { get; set; }
        public virtual DbSet<DET_APROB> DET_APROB { get; set; }
        public virtual DbSet<DET_APROBH> DET_APROBH { get; set; }
        public virtual DbSet<DET_APROBP> DET_APROBP { get; set; }
        public virtual DbSet<DET_TAX> DET_TAX { get; set; }
        public virtual DbSet<DET_TAXEO> DET_TAXEO { get; set; }
        public virtual DbSet<DET_TAXEOC> DET_TAXEOC { get; set; }
        public virtual DbSet<DOCTOAYUDA> DOCTOAYUDAs { get; set; }
        public virtual DbSet<DOCTOCLASIF> DOCTOCLASIFs { get; set; }
        public virtual DbSet<DOCTOCLASIFT> DOCTOCLASIFTs { get; set; }
        public virtual DbSet<DOCUMENTBORR> DOCUMENTBORRs { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTOes { get; set; }
        public virtual DbSet<DOCUMENTOA> DOCUMENTOAs { get; set; }
        public virtual DbSet<DOCUMENTOBORRF> DOCUMENTOBORRFs { get; set; }
        public virtual DbSet<DOCUMENTOBORRM> DOCUMENTOBORRMs { get; set; }
        public virtual DbSet<DOCUMENTOBORRN> DOCUMENTOBORRNs { get; set; }
        public virtual DbSet<DOCUMENTOBORRP> DOCUMENTOBORRPs { get; set; }
        public virtual DbSet<DOCUMENTOBORRREC> DOCUMENTOBORRRECs { get; set; }
        public virtual DbSet<DOCUMENTOF> DOCUMENTOFs { get; set; }
        public virtual DbSet<DOCUMENTOL> DOCUMENTOLs { get; set; }
        public virtual DbSet<DOCUMENTOM> DOCUMENTOMs { get; set; }
        public virtual DbSet<DOCUMENTON> DOCUMENTONs { get; set; }
        public virtual DbSet<DOCUMENTOP> DOCUMENTOPs { get; set; }
        public virtual DbSet<DOCUMENTOR> DOCUMENTORs { get; set; }
        public virtual DbSet<DOCUMENTORAN> DOCUMENTORANs { get; set; }
        public virtual DbSet<DOCUMENTOREC> DOCUMENTORECs { get; set; }
        public virtual DbSet<DOCUMENTOSAP> DOCUMENTOSAPs { get; set; }
        public virtual DbSet<DOCUMENTOT> DOCUMENTOTS { get; set; }
        public virtual DbSet<ESTATU> ESTATUS { get; set; }
        public virtual DbSet<ESTATUSR> ESTATUSRs { get; set; }
        public virtual DbSet<ESTATUST> ESTATUSTs { get; set; }
        public virtual DbSet<FACTURASCONF> FACTURASCONFs { get; set; }
        public virtual DbSet<FLUJNEGO> FLUJNEGOes { get; set; }
        public virtual DbSet<FLUJO> FLUJOes { get; set; }
        public virtual DbSet<GALL> GALLs { get; set; }
        public virtual DbSet<GALLT> GALLTs { get; set; }
        public virtual DbSet<GAUTORIZACION> GAUTORIZACIONs { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<GrupoCat> GrupoCats { get; set; }
        public virtual DbSet<IIMPUESTO> IIMPUESTOes { get; set; }
        public virtual DbSet<IMPUESTO> IMPUESTOes { get; set; }
        public virtual DbSet<LAYOUT_CARGA> LAYOUT_CARGA { get; set; }
        public virtual DbSet<LEYENDA> LEYENDAs { get; set; }
        public virtual DbSet<MATERIAL> MATERIALs { get; set; }
        public virtual DbSet<MATERIALGP> MATERIALGPs { get; set; }
        public virtual DbSet<MATERIALGPT> MATERIALGPTs { get; set; }
        public virtual DbSet<MATERIALT> MATERIALTs { get; set; }
        public virtual DbSet<MATERIALVKE> MATERIALVKEs { get; set; }
        public virtual DbSet<MENSAJE> MENSAJES { get; set; }
        public virtual DbSet<MIEMBRO> MIEMBROS { get; set; }
        public virtual DbSet<MONEDA> MONEDAs { get; set; }
        public virtual DbSet<NEGOCIACION> NEGOCIACIONs { get; set; }
        public virtual DbSet<NEGOCIACION2> NEGOCIACION2 { get; set; }
        public virtual DbSet<NOTICIA> NOTICIAs { get; set; }
        public virtual DbSet<PAGINA> PAGINAs { get; set; }
        public virtual DbSet<PAGINAT> PAGINATs { get; set; }
        public virtual DbSet<PAI> PAIS { get; set; }
        public virtual DbSet<PERIODO> PERIODOes { get; set; }
        public virtual DbSet<PERIODO445> PERIODO445 { get; set; }
        public virtual DbSet<PERIODOT> PERIODOTs { get; set; }
        public virtual DbSet<PERMISO_PAGINA> PERMISO_PAGINA { get; set; }
        public virtual DbSet<POSICION> POSICIONs { get; set; }
        public virtual DbSet<PRESUPSAPH> PRESUPSAPHs { get; set; }
        public virtual DbSet<PRESUPSAPP> PRESUPSAPPs { get; set; }
        public virtual DbSet<PRESUPUESTOH> PRESUPUESTOHs { get; set; }
        public virtual DbSet<PRESUPUESTOP> PRESUPUESTOPs { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<PUESTOT> PUESTOTs { get; set; }
        public virtual DbSet<RANGO> RANGOes { get; set; }
        public virtual DbSet<REGION> REGIONs { get; set; }
        public virtual DbSet<RETENCION> RETENCIONs { get; set; }
        public virtual DbSet<RETENCIONT> RETENCIONTs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<ROLT> ROLTs { get; set; }
        public virtual DbSet<SOCIEDAD> SOCIEDADs { get; set; }
        public virtual DbSet<SPRA> SPRAS { get; set; }
        public virtual DbSet<STATE> STATES { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAB> TABs { get; set; }
        public virtual DbSet<TALL> TALLs { get; set; }
        public virtual DbSet<TALLT> TALLTs { get; set; }
        public virtual DbSet<TAX_LAND> TAX_LAND { get; set; }
        public virtual DbSet<TAXEOH> TAXEOHs { get; set; }
        public virtual DbSet<TAXEOP> TAXEOPs { get; set; }
        public virtual DbSet<TCAMBIO> TCAMBIOs { get; set; }
        public virtual DbSet<TCLIENTE> TCLIENTEs { get; set; }
        public virtual DbSet<TCLIENTET> TCLIENTETs { get; set; }
        public virtual DbSet<TEXTO> TEXTOes { get; set; }
        public virtual DbSet<TEXTOCV> TEXTOCVs { get; set; }
        public virtual DbSet<TRETENCION> TRETENCIONs { get; set; }
        public virtual DbSet<TRETENCIONT> TRETENCIONTs { get; set; }
        public virtual DbSet<TREVERSA> TREVERSAs { get; set; }
        public virtual DbSet<TREVERSAT> TREVERSATs { get; set; }
        public virtual DbSet<TS_CAMPO> TS_CAMPO { get; set; }
        public virtual DbSet<TS_FORM> TS_FORM { get; set; }
        public virtual DbSet<TS_FORMT> TS_FORMT { get; set; }
        public virtual DbSet<TSOL> TSOLs { get; set; }
        public virtual DbSet<TSOL_GROUP> TSOL_GROUP { get; set; }
        public virtual DbSet<TSOL_GROUPT> TSOL_GROUPT { get; set; }
        public virtual DbSet<TSOL_TREE> TSOL_TREE { get; set; }
        public virtual DbSet<TSOLT> TSOLTs { get; set; }
        public virtual DbSet<TSOPORTE> TSOPORTEs { get; set; }
        public virtual DbSet<TSOPORTET> TSOPORTETs { get; set; }
        public virtual DbSet<TX_CONCEPTO> TX_CONCEPTO { get; set; }
        public virtual DbSet<TX_CONCEPTOT> TX_CONCEPTOT { get; set; }
        public virtual DbSet<TX_NOTAT> TX_NOTAT { get; set; }
        public virtual DbSet<TX_TNOTA> TX_TNOTA { get; set; }
        public virtual DbSet<UMEDIDA> UMEDIDAs { get; set; }
        public virtual DbSet<UMEDIDAT> UMEDIDATs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIOF> USUARIOFs { get; set; }
        public virtual DbSet<USUARIOLOG> USUARIOLOGs { get; set; }
        public virtual DbSet<USUARIOSAP> USUARIOSAPs { get; set; }
        public virtual DbSet<WARNING> WARNINGs { get; set; }
        public virtual DbSet<WARNING_COND> WARNING_COND { get; set; }
        public virtual DbSet<WARNINGP> WARNINGPs { get; set; }
        public virtual DbSet<WARNINGPT> WARNINGPTs { get; set; }
        public virtual DbSet<WORKFH> WORKFHs { get; set; }
        public virtual DbSet<WORKFP> WORKFPs { get; set; }
        public virtual DbSet<WORKFT> WORKFTs { get; set; }
        public virtual DbSet<WORKFV> WORKFVs { get; set; }
        public virtual DbSet<ZBRAND> ZBRANDs { get; set; }
        public virtual DbSet<ZCTGR> ZCTGRs { get; set; }
        public virtual DbSet<TAB_CAMPO> TAB_CAMPO { get; set; }
    }
}
